version: "0.5"

processes:
  php-fpm:
    command: "php-fpm -R -y $PHPFPM --nodaemonize"
    availability:
      restart: "always"
  php-fpm81:
    command: "php-fpm -R -y $PHPFPM81 --nodaemonize"
    availability:
      restart: "always"
  nginx:
    command: |
      if [ -f $NGINX_CONFDIR/nginx.template ]; then envsubst $(awk 'BEGIN {for (k in ENVIRON) {printf "$"k","}}') < $NGINX_CONFDIR/nginx.template > $NGINX_CONFDIR/nginx.conf; fi
      nginx -p $NGINX_PATH_PREFIX -c $NGINX_CONFDIR/nginx.conf -e error.log -g "pid nginx.pid;daemon off;"
    availability:
      restart: on_failure
      max_restarts: 5
  nginx-error:
    command: "tail -f $NGINX_PATH_PREFIX/error.log"
    availability:
      restart: "always"
  nginx-access:
    command: "tail -f $NGINX_PATH_PREFIX/access.log"
    availability:
      restart: "always"
