theme = "ayu_dark"

[editor]
mouse = false
true-color = true
cursorline = true
bufferline = "multiple"
rulers = [80, 120]
auto-format = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = false

[editor.file-picker]
hidden = false

[keys.normal]
"=" = [
  "extend_to_line_bounds",
  "format_selections",
  # "add_newline_below",
  ":pipe sed -e 's/\t/    /g'"
]
C-r = [
  "wonly",
  ":set-language sql",
  ":buffer-close-others!",
  "extend_to_line_bounds",
  "yank",
  ":hsplit-new",
  "paste_after",
  # ":pipe myq",
  ":pipe mysql -u\"${MYSQL_USER:-test}\" \"${MYSQL_DB:-test}\" -e \"$(cat)\"",
  "rotate_view"
]
C-j = [
  "wonly",
  ":set-language jsonnet",
  ":buffer-close-others!",
  "extend_to_line_bounds",
  "yank",
  ":vsplit-new",
  ":set-language jsonnet",
  "paste_after",
  ":pipe myr",
  "goto_file_start",
  "rotate_view",
]

[keys.normal."ret"]
f = { n = "@%s\\\\n<ret>c<ret><esc>,", t = "@%s\\t<ret>&," }
w = ":w"
q = ":q"
Q = ":qa!"
c = ":bc"
C = ":bc!"
o = ":bco"
O = ":bco!"
r = ":rl"
R = ":rla"
# j = ":sh cargo run"

H = { r = ":config-reload", o = ":config-open" }

