theme = "tokyonight_storm"

[editor]
mouse = false
true-color = true
cursorline = true
bufferline = "multiple"

[keys.normal."ret"]
w = ":w"
q = ":q"
c = ":bc"
o = ":bco"
r = ":rl"
H = { r = ":config-reload", o = ":config-open" }
