theme = "ayu_dark"

[editor]
mouse = false
true-color = true
cursorline = true
bufferline = "multiple"
rulers = [80, 120]

[editor.smart-tab]
enable = false

[editor.file-picker]
hidden = false

[keys.normal."ret"]
w = ":w"
q = ":q"
c = ":bc"
o = ":bco"
r = ":rl"
R = ":rla"
j = [
  "wonly", "vsplit_new",
  ":insert-output curl -s -X GET http://127.0.0.1:60023/api/test",
  ":append-output echo 'test'",
  "rotate_view"
]
H = { r = ":config-reload", o = ":config-open" }

