theme = "ayu_dark"

[editor]
mouse = false
true-color = true
cursorline = true
bufferline = "multiple"
rulers = [80, 120]

[editor.smart-tab]
enable = false

[keys.normal."ret"]
w = ":w"
q = ":q"
c = ":bc"
o = ":bco"
r = ":rl"
R = ":rla"
H = { r = ":config-reload", o = ":config-open" }

