theme = "tokyonight_storm"

[editor]
mouse = false
true-color = true
cursorline = true
bufferline = "multiple"

[keys.normal."ret"]
w = ":w"
q = ":q"
b = { n = ":bn", p = ":bp", c = ":bc", l = "buffer_picker" }
