theme = "ayu_dark"

[editor]
mouse = false
true-color = true
cursorline = true
bufferline = "multiple"
rulers = [80, 120]
auto-format = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = false

[editor.file-picker]
hidden = false

[keys.normal."ret"]
w = ":w"
q = ":q"
Q = ":qa!"
c = ":bc"
C = ":bc!"
o = ":bco"
O = ":bco!"
r = ":rl"
R = ":rla"
# j = ":sh cargo run"
C-r = [
  "wonly",
  "extend_to_line_bounds",
  "yank",
  ":hsplit-new",
  "paste_after",
  ":pipe myq",
  "rotate_view"
]
C-j = [
  "wonly",
  "extend_to_line_bounds",
  "yank",
  ":vsplit-new",
  "paste_after",
  ":pipe myr",
  "goto_file_start",
  "rotate_view"
]

H = { r = ":config-reload", o = ":config-open" }

