
# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "php"
file-types = ["php"]
# config = { enable = true, lint = true, unstable = true }
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "rest"
grammar = "jsonc"
scope = "source.rest"
injection-regex = "rest"
file-types = ["rest", "jsonc"]
comment-tokens = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = [ { "name" = "vscode-json-language-server", "only-features" = [ "document-highlight", "format" ] } ]
